data:
  dataname: "linemod"
  # 这个是数据集的位置，下一级的数据是需要使用代码搜索的
  dataset_dir: "/media/wangxiao/Newsmy/linemod/raw/lm_train/train"
  # 因为每个onepose的数据集下面有几个subdir，名字后面加上 -1 -2等
  subdir: ""
  # 这个是每一个子数据下面的照片的路径
  color: "rgb"
  # 每一个3dgs的
  gsdir: "/media/wangxiao/Newsmy/dataset_LINEMOD/datasets/linemod_pgsr"
  gs_subdir: "test/point_cloud/iteration_30000/point_cloud.ply"

  colmap_path: "/media/wangxiao/Newsmy/linemod/linemod_train_sfm"


  # 这个是每一个子数据下面的相机参数的路径
  pose: "scene_gt.json"
  intrin: "scene_camera.json"
  box_dir: "/media/wangxiao/Newsmy/linemod/raw/lm_models/models/models_info.json"

  maskforder_dir: "mask"

  clip: True

debug: False
match:
  extractor:
    name: "SuperPoint"
    max_num_keypoints: 2048
  matcher: 
    name: "LightGlue"
    features: "superpoint"
  confidence_threshold: 0.90

  camera_num: 10
  pnp_reprojection_error: 5
  use_pose_refine: True


metric_out_dir: ""








